name: GO GREEENNNNNn

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  auto_push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Sequential Pushes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          for i in {1..8}
          do
            echo "I LOVE MATCHAAAAAA $i/8 at $(date)" > last_update.txt
            git add last_update.txt
            git commit -m "I LOVE MATCHAAAAAA $i/8 at $(date)"
            git push
            # Optional: sleep for a few seconds to ensure distinct timestamps
            sleep 2
          done
